# You can lint your .gitlab-ci.yml file here:
# https://gitlab.iscpif.fr/gargantext/haskell-pgmq/-/ci/lint

cache:
  paths:
    - dist-newstyle/

stages:
  - build
  - unit-tests
  - integration-tests

build:
  stage: build
  image: haskell:9.4.8-slim
  # https://stackoverflow.com/questions/76340763/what-gitlab-ci-configuration-will-reliably-cache-haskell-package-dependencies-bu
  cache:
    key: "v0-cabal"
    paths:
      - ".cabal"
  before_script:
    - |
      cat >cabal.project.local <<EOF
      store-dir: $CI_PROJECT_DIR/.cabal
      remote-repo-cache: $CI_PROJECT_DIR/.cabal/packages
      EOF  
    - apt-get update -qq && apt-get install -y -qq libpq-dev
    - cabal update
  script:
    - cabal v2-build all

unit-tests:
  stage: unit-tests
  image: haskell:9.4.8-slim
  # https://stackoverflow.com/questions/76340763/what-gitlab-ci-configuration-will-reliably-cache-haskell-package-dependencies-bu
  cache:
    key: "v0-cabal"
    paths:
      - ".cabal"
  before_script:
    - |
      cat >cabal.project.local <<EOF
      store-dir: $CI_PROJECT_DIR/.cabal
      remote-repo-cache: $CI_PROJECT_DIR/.cabal/packages
      EOF  
    - apt-get update -qq && apt-get install -y -qq libpq-dev
    - cabal update
  script:
    #- cabal v2-test test-pgmq-unit
    - cabal v2-run haskell-bee:test-unit -- +RTS -N -RTS
    - cabal v2-run haskell-bee-redis:redis-test-unit -- +RTS -N -RTS
    - cabal v2-run haskell-bee-stm:stm-test-unit -- +RTS -N -RTS

integration-tests-pgmq:
  stage: integration-tests
  image: haskell:9.4.8-slim
  services:
    - name: docker.io/cgenie/pgmq:16-1.3.3.1
      alias: pgmq
    #- name: docker.io/redis:7.2
    #  alias: redis
  variables:
    # https://stackoverflow.com/questions/77173109/error-link-is-not-supported-in-gitlab-ci-cd-pipeline-when-executing-an-image-as
    FF_NETWORK_PER_BUILD: 1
    # Configure postgres service (https://hub.docker.com/_/postgres/)
    POSTGRES_DB: pgmq
    POSTGRES_USER: pgmq
    POSTGRES_PASSWORD: pgmq
  # https://stackoverflow.com/questions/76340763/what-gitlab-ci-configuration-will-reliably-cache-haskell-package-dependencies-bu
  cache:
    key: "v0-cabal"
    paths:
      - ".cabal"
  before_script:
    - |
      cat >cabal.project.local <<EOF
      store-dir: $CI_PROJECT_DIR/.cabal
      remote-repo-cache: $CI_PROJECT_DIR/.cabal/packages
      EOF  
    - apt-get update -qq && apt-get install -y -qq libpq-dev
    - cabal update
  script:
    - export POSTGRES_HOST=pgmq
    - export REDIS_HOST=redis
    #- cabal v2-test test-pgmq-integration
    # cabal v2-test -j seems not to work correctly, so we just run the integration test
    - cabal v2-run haskell-bee-pgmq:pgmq-test-integration -- +RTS -N -RTS
